--[[ The 'Combine' class will ensure any combine character with the words 'SCN' or 'SHIELD' in their name will not be able to use the regular netropolice voices
I find it stupid that scanners can use the metropolice voices by default and decided its best to just add it to the plugin

If you wish scanners to be able to use the MPF sounds feel free to remove the entire 'Combine' class, just take note it may break your voices file and you will have to do some changes of your own to the scanner codes.
If your scanners use different ranks, edit the 'Scanner' class strings to whatever ranks you have and be sure to do the same to the 'Combine' class if you didn't delete it.
--]]


Schema.voices.Add("Scanner", "0", "Zero", "ceryx/combot/combot_zero.mp3")
Schema.voices.Add("Scanner", "1", "One", "ceryx/combot/combot_one.mp3")
Schema.voices.Add("Scanner", "2", "Two", "ceryx/combot/combot_two.mp3")
Schema.voices.Add("Scanner", "3", "Three", "ceryx/combot/combot_three.mp3")
Schema.voices.Add("Scanner", "4", "Four", "ceryx/combot/combot_four.mp3")
Schema.voices.Add("Scanner", "5", "Five", "ceryx/combot/combot_five.mp3")
Schema.voices.Add("Scanner", "6", "Six", "ceryx/combot/combot_six.mp3")
Schema.voices.Add("Scanner", "7", "Seven", "ceryx/combot/combot_seven.mp3")
Schema.voices.Add("Scanner", "8", "Eight", "ceryx/combot/combot_eight.mp3")
Schema.voices.Add("Scanner", "9", "Nine", "ceryx/combot/combot_nine.mp3")
Schema.voices.Add("Scanner", "10", "Ten", "ceryx/combot/combot_ten.mp3")
Schema.voices.Add("Scanner", "ADNINISTER", "Administer", "ceryx/combot/combot_administer.mp3")
Schema.voices.Add("Scanner", "BIOTIC", "Biotic", "ceryx/combot/combot_biotic.mp3")
Schema.voices.Add("Scanner", "BIOTICS", "Biotics", "ceryx/combot/combot_biotics.mp3")
Schema.voices.Add("Scanner", "CAUTERIZE", "Cauterize", "ceryx/combot/combot_cauterize.mp3")
Schema.voices.Add("Scanner", "DIAGNOSE", "Diagnose", "ceryx/combot/combot_diagnose.mp3")
Schema.voices.Add("Scanner", "EXOGEN", "Exogen", "ceryx/combot/combot_exogen.mp3")
Schema.voices.Add("Scanner", "INFECTED", "Infected", "ceryx/combot/combot_infected.mp3")
Schema.voices.Add("Scanner", "INTERCEDE", "Intercede", "ceryx/combot/combot_intercede.mp3")
Schema.voices.Add("Scanner", "INTERLOCK", "Interlock", "ceryx/combot/combot_interlock.mp3")
Schema.voices.Add("Scanner", "INVESTIGATE", "Investigate", "ceryx/combot/combot_investigate.mp3")
Schema.voices.Add("Scanner", "MIDNIGHT", "Midnight", "ceryx/combot/combot_midnight.mp3")
Schema.voices.Add("Scanner", "NECROTICS", "Necrotics", "ceryx/combot/combot_necrotics.mp3")
Schema.voices.Add("Scanner", "NECROTIC", "Necrotic", "ceryx/combot/combot_necrotic.mp3")
Schema.voices.Add("Scanner", "PACIFY", "Pacify", "ceryx/combot/combot_pacify.mp3")
Schema.voices.Add("Scanner", "PARASITICS", "Parasitics", "ceryx/combot/combot_parasitics.mp3")
Schema.voices.Add("Scanner", "PARASITIC", "Parasitic", "ceryx/combot/combot_parasitic.mp3")
Schema.voices.Add("Scanner", "STERILIZE", "Sterilize", "ceryx/combot/combot_sterilize.mp3")
Schema.voices.Add("Scanner", "ALPHA", "Alpha", "ceryx/combot/combot_alpha.mp3")
Schema.voices.Add("Scanner", "APEX", "Apex", "ceryx/combot/combot_apex.mp3")
Schema.voices.Add("Scanner", "BLADE", "Blade", "ceryx/combot/combot_blade.mp3")
Schema.voices.Add("Scanner", "BRAVO", "Bravo", "ceryx/combot/combot_bravo.mp3")
Schema.voices.Add("Scanner", "DAGGER", "Dagger", "ceryx/combot/combot_dagger.mp3")
Schema.voices.Add("Scanner", "DASH", "Dash", "ceryx/combot/combot_dash.mp3")
Schema.voices.Add("Scanner", "DELTA", "Delta", "ceryx/combot/combot_delta.mp3")
Schema.voices.Add("Scanner", "ECHO", "Echo", "ceryx/combot/combot_echo.mp3")
Schema.voices.Add("Scanner", "GHOST", "Ghost", "ceryx/combot/combot_ghost.mp3")
Schema.voices.Add("Scanner", "GRID", "Grid", "ceryx/combot/combot_grid.mp3")
Schema.voices.Add("Scanner", "HELIX", "Helix", "ceryx/combot/combot_helix.mp3")
Schema.voices.Add("Scanner", "HERO", "Hero", "ceryx/combot/combot_hero.mp3")
Schema.voices.Add("Scanner", "JUDGE", "Judge", "ceryx/combot/combot_judge.mp3")
Schema.voices.Add("Scanner", "JURY", "Jury", "ceryx/combot/combot_jury.mp3")
Schema.voices.Add("Scanner", "KING", "King", "ceryx/combot/combot_king.mp3")
Schema.voices.Add("Scanner", "MACE", "Mace", "ceryx/combot/combot_mace.mp3")
Schema.voices.Add("Scanner", "NOVA", "Nova", "ceryx/combot/combot_nova.mp3")
Schema.voices.Add("Scanner", "OVERWATCH", "Overwatch", "ceryx/combot/combot_overwatch.mp3")
Schema.voices.Add("Scanner", "PHANTOM", "Phantom", "ceryx/combot/combot_phantom.mp3")
Schema.voices.Add("Scanner", "SWORD", "Sword", "ceryx/combot/combot_sword.mp3")
Schema.voices.Add("Scanner", "UNION", "Union", "ceryx/combot/combot_union.mp3")
Schema.voices.Add("Scanner", "XRAY", "Xray", "ceryx/combot/combot_xray.mp3")
Schema.voices.Add("Scanner", "ANTI CITIZEN", "Anti-Citizen", "ceryx/combot/combot_anticitizen.mp3")
Schema.voices.Add("Scanner", "CITIZEN", "Citizen", "ceryx/combot/combot_citizen.mp3")
Schema.voices.Add("Scanner", "FINAL VERDICT", "Administer final verdict", "ceryx/combot/combot_finalverdict.mp3")
Schema.voices.Add("Scanner", "LOST VISUAL", "Lost visual on suspect", "ceryx/combot/combot_lostvisual.mp3")
Schema.voices.Add("Scanner", "MENTALLY UNFIT", "Disturbance by mentally unfit", "ceryx/combot/combot_mental.mp3")
Schema.voices.Add("Scanner", "MOVE ALONG", "Move along", "ceryx/combot/combot_movealong.mp3")
Schema.voices.Add("Scanner", "PROCEED", "You may proceed", "ceryx/combot/combot_proceed.mp3")
Schema.voices.Add("Scanner", "PROSECUTING", "Prosecuting", "ceryx/combot/combot_prosecuting.mp3")
Schema.voices.Add("Scanner", "SOCIOSCAN", "Recalibrate socioscan", "ceryx/combot/combot_socioscan.mp3")
Schema.voices.Add("Scanner", "VISUAL", "Visual on suspect", "ceryx/combot/combot_visual.mp3")
Schema.voices.Add("Scanner", "APPLY", "Apply", "ceryx/combot/combot_apply.mp3")
Schema.voices.Add("Scanner", "APPLYID", "Apply and present your ID", "ceryx/combot/combot_applyandid.mp3")
Schema.voices.Add("Scanner", "COA", "Cooperate, Obey, Apply!", "ceryx/combot/combot_cooprateandapply.mp3")
Schema.voices.Add("Scanner", "CITIZENSHIP", "Citizenship confirmed, you may proceed", "ceryx/combot/combot_citizenshipconf.mp3")
Schema.voices.Add("Scanner", "UNRECOGNIZED", "Warning. Incompatible details. Contacting local authorities", "ceryx/combot/combot_cannotrecognize.mp3")
Schema.voices.Add("Scanner", "FINAL WARNING", "This is your final warning", "ceryx/combot/combot_finalwarning.mp3")
Schema.voices.Add("Scanner", "REFUSAL", "Refusal to identity is an anti-civil violation", "ceryx/combot/combot_refusal.mp3")
Schema.voices.Add("Scanner", "STAND BY", "Stand by and await approval", "ceryx/combot/combot_standby.mp3")
Schema.voices.Add("Scanner", "DNBIOTIC", "Do not interact with the biotic", "ceryx/combot/combot_biotic.mp3")
Schema.voices.Add("Scanner", "DIALOUGE", "This unit was not intended for dialogue. Move along!", "ceryx/combot/combot_dialogue.mp3")
Schema.voices.Add("Scanner", "RESTRICTED", "This is a restricted area. Turn back!", "ceryx/combot/combot_restrictedarea.mp3")
Schema.voices.Add("Scanner", "INDOCTRINATION", "Warning. Ongoing violations is entitled to indoctrination", "ceryx/combot/combot_indoctrination.mp3")
Schema.voices.Add("Scanner", "INTERVENTION", "Warning. Unauthorized intervention. Step back!", "ceryx/combot/combot_intervention.mp3")
Schema.voices.Add("Scanner", "MALCOMPLIANCE", "Malcompliance Noted. Contacting local authorities", "ceryx/combot/combot_malconoted.mp3")
Schema.voices.Add("Scanner", "SOCIOCIDEN", "Sociocide Noted. Do not move! Await Prosecution", "ceryx/combot/combot_socio.mp3")
Schema.voices.Add("Scanner", "AMPUTATE", "Amputate", "ceryx/combot/combot_amputate.mp3")

Schema.voices.AddClass("Combine", function(client)
return client:IsCombine() and !Schema:IsCombineRank(client:Name(), "SCN") and !Schema:IsCombineRank(client:Name(), "SHIELD") 
end)

Schema.voices.AddClass("Scanner", function(client)
	return Schema:IsCombineRank(client:Name(), "SCN") or Schema:IsCombineRank(client:Name(), "SHIELD")
end)